In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [16]:
data_set = pd.read_csv(r"D:\MSc\Semester 1\CS5612 - Pattern Recognition\Assignment 4\WBCD\breast-cancer-wisconsin.data_MISSING_DATA_ROWS_REPLACED.csv")

In [17]:
data_clean = data_set.dropna()

In [18]:
X = data_clean.drop('target', axis=1)
y = data_clean['target']

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.35)

In [20]:
kNNModel = KNeighborsClassifier(n_neighbors=3)
kNNModel.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [21]:
y_pred = kNNModel.predict(X_test)

In [22]:
print(kNNModel.score(X_test, y_test))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.5836734693877551
[[114  48]
 [ 54  29]]
              precision    recall  f1-score   support

           2       0.68      0.70      0.69       162
           4       0.38      0.35      0.36        83

    accuracy                           0.58       245
   macro avg       0.53      0.53      0.53       245
weighted avg       0.58      0.58      0.58       245



In [23]:
nbModel = GaussianNB()
nbModel.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [24]:
y_pred = nbModel.predict(X_test)

In [123]:
print(nbModel.score(X_test, y_test))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8
[[129  33]
 [ 16  67]]
              precision    recall  f1-score   support

           2       0.89      0.80      0.84       162
           4       0.67      0.81      0.73        83

    accuracy                           0.80       245
   macro avg       0.78      0.80      0.79       245
weighted avg       0.82      0.80      0.80       245



In [26]:
lrModel = LogisticRegression(random_state=0, solver='lbfgs')
lrModel.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [13]:
y_pred = lrModel.predict(X_test)

In [14]:
print(lrModel.score(X_test, y_test))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6244897959183674
[[153   0]
 [ 92   0]]
              precision    recall  f1-score   support

           2       0.62      1.00      0.77       153
           4       0.00      0.00      0.00        92

    accuracy                           0.62       245
   macro avg       0.31      0.50      0.38       245
weighted avg       0.39      0.62      0.48       245



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
