In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from neupy import algorithms
from sklearn import metrics

In [2]:
data_set = pd.read_csv("breast-cancer-wisconsin.data_MISSING_DATA_ROWS_REPLACED.csv")

In [3]:
data_clean = data_set.dropna()

In [4]:
X = data_clean.drop('target', axis=1)
y = data_clean['target']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.35)

In [6]:
kNNModel = KNeighborsClassifier(n_neighbors=3)
kNNModel.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [7]:
y_pred = kNNModel.predict(X_test)

In [8]:
print(kNNModel.score(X_test, y_test))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6204081632653061
[[123  36]
 [ 57  29]]
              precision    recall  f1-score   support

           2       0.68      0.77      0.73       159
           4       0.45      0.34      0.38        86

    accuracy                           0.62       245
   macro avg       0.56      0.56      0.55       245
weighted avg       0.60      0.62      0.61       245



In [9]:
nbModel = GaussianNB()
nbModel.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [10]:
y_pred = nbModel.predict(X_test)

In [11]:
print(nbModel.score(X_test, y_test))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7795918367346939
[[120  39]
 [ 15  71]]
              precision    recall  f1-score   support

           2       0.89      0.75      0.82       159
           4       0.65      0.83      0.72        86

    accuracy                           0.78       245
   macro avg       0.77      0.79      0.77       245
weighted avg       0.80      0.78      0.78       245



In [12]:
lrModel = LogisticRegression(random_state=0, solver='lbfgs')
lrModel.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [13]:
y_pred = lrModel.predict(X_test)

In [14]:
print(lrModel.score(X_test, y_test))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6489795918367347
[[159   0]
 [ 86   0]]
              precision    recall  f1-score   support

           2       0.65      1.00      0.79       159
           4       0.00      0.00      0.00        86

    accuracy                           0.65       245
   macro avg       0.32      0.50      0.39       245
weighted avg       0.42      0.65      0.51       245



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [16]:
data_set_lvq = pd.read_csv("breast-cancer-wisconsin.data_MISSING_DATA_ROWS_REPLACED_LVQ.csv")
data_clean_lvq = data_set_lvq.dropna()

_X = data_clean_lvq.drop('target', axis=1)
_y = data_clean_lvq['target']

_X_train, _X_test, _y_train, _y_test = train_test_split(_X, _y, test_size = 0.35)

lvqnet = algorithms.LVQ(n_inputs=9, n_classes=2)
lvqnet.train(_X_train, _y_train, epochs=100)
_y_pred = lvqnet.predict(_X_test)

print(confusion_matrix(_y_test,_y_pred))
print(metrics.accuracy_score(_y_test, _y_pred)*100.0)

[[161   2]
 [ 78   4]]
67.3469387755102
