In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [16]:
data_set = pd.read_csv(r"D:\MSc\Semester 1\CS5612 - Pattern Recognition\Assignment 4\WBCD\breast-cancer-wisconsin.data_MISSING_DATA_ROWS_REMOVED.csv")

In [17]:
data_clean = data_set.dropna()

In [18]:
X = data_clean.drop('target', axis=1)
y = data_clean['target']

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.35)

In [20]:
kNNModel = KNeighborsClassifier(n_neighbors=3)
kNNModel.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [21]:
y_pred = kNNModel.predict(X_test)

In [22]:
print(kNNModel.score(X_test, y_test))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6
[[121  39]
 [ 57  23]]
              precision    recall  f1-score   support

           2       0.68      0.76      0.72       160
           4       0.37      0.29      0.32        80

    accuracy                           0.60       240
   macro avg       0.53      0.52      0.52       240
weighted avg       0.58      0.60      0.59       240



In [23]:
nbModel = GaussianNB()
nbModel.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [24]:
y_pred = nbModel.predict(X_test)

In [25]:
print(nbModel.score(X_test, y_test))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7458333333333333
[[107  53]
 [  8  72]]
              precision    recall  f1-score   support

           2       0.93      0.67      0.78       160
           4       0.58      0.90      0.70        80

    accuracy                           0.75       240
   macro avg       0.75      0.78      0.74       240
weighted avg       0.81      0.75      0.75       240



In [26]:
lrModel = LogisticRegression(random_state=0, solver='lbfgs')
lrModel.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [27]:
y_pred = lrModel.predict(X_test)

In [14]:
print(lrModel.score(X_test, y_test))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6333333333333333
[[152   0]
 [ 88   0]]
              precision    recall  f1-score   support

           2       0.63      1.00      0.78       152
           4       0.00      0.00      0.00        88

    accuracy                           0.63       240
   macro avg       0.32      0.50      0.39       240
weighted avg       0.40      0.63      0.49       240



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
