In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from neupy import algorithms
from sklearn import metrics

In [97]:
data_set = pd.read_csv("breast-cancer-wisconsin.data_MISSING_DATA_ROWS_REMOVED.csv")

In [98]:
data_clean = data_set.dropna()

In [99]:
X = data_clean.drop('target', axis=1)
y = data_clean['target']

In [100]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.35)

In [101]:
kNNModel = KNeighborsClassifier(n_neighbors=3)
kNNModel.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [102]:
y_pred = kNNModel.predict(X_test)

In [103]:
print(kNNModel.score(X_test, y_test))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6
[[113  43]
 [ 53  31]]
              precision    recall  f1-score   support

           2       0.68      0.72      0.70       156
           4       0.42      0.37      0.39        84

    accuracy                           0.60       240
   macro avg       0.55      0.55      0.55       240
weighted avg       0.59      0.60      0.59       240



In [104]:
nbModel = GaussianNB()
nbModel.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [105]:
y_pred = nbModel.predict(X_test)

In [106]:
print(nbModel.score(X_test, y_test))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6833333333333333
[[92 64]
 [12 72]]
              precision    recall  f1-score   support

           2       0.88      0.59      0.71       156
           4       0.53      0.86      0.65        84

    accuracy                           0.68       240
   macro avg       0.71      0.72      0.68       240
weighted avg       0.76      0.68      0.69       240



In [107]:
lrModel = LogisticRegression(random_state=0, solver='lbfgs')
lrModel.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [108]:
y_pred = lrModel.predict(X_test)

In [109]:
print(lrModel.score(X_test, y_test))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.65
[[156   0]
 [ 84   0]]
              precision    recall  f1-score   support

           2       0.65      1.00      0.79       156
           4       0.00      0.00      0.00        84

    accuracy                           0.65       240
   macro avg       0.33      0.50      0.39       240
weighted avg       0.42      0.65      0.51       240



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [110]:
data_set_lvq = pd.read_csv("breast-cancer-wisconsin.data_MISSING_DATA_ROWS_REMOVED_LVQ.csv")
data_clean_lvq = data_set_lvq.dropna()

_X = data_clean_lvq.drop('target', axis=1)
_y = data_clean_lvq['target']

_X_train, _X_test, _y_train, _y_test = train_test_split(_X, _y, test_size = 0.35)

lvqnet = algorithms.LVQ(n_inputs=9, n_classes=2)
lvqnet.train(_X_train, _y_train, epochs=100)
_y_pred = lvqnet.predict(_X_test)

print(confusion_matrix(_y_test,_y_pred))
print(metrics.accuracy_score(_y_test, _y_pred)*100.0)

[[138  11]
 [ 81  10]]
61.66666666666667
